name: gutenberg
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.9.0
  google_fonts: ^6.0.0
  http: ^1.5.0
  intl: ^0.20.2
  intl_phone_number_input: ^0.7.4
  lottie: ^3.3.1
  phonenumbers: ^1.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/images/
